from __future__ import annotations


_STORIES = (
    (
        "practice",
        "practice-01",
        "冒险",
        "adventure-beach",
        "海滩上的一场冒险",
        "退潮后偶然发现一件奇物，主角循线追查，意外卷入一段未知旅程。",
    ),
    (
        "formal",
        "formal-01",
        "冒险",
        "adventure-forest",
        "森林里的一场冒险",
        "偏离原路后发现异常痕迹，寻找出口的途中走入更深的谜团。",
    ),
    (
        "formal",
        "formal-02",
        "冒险",
        "adventure-space",
        "太空中的一场冒险",
        "飞船接收到陌生信号，船员追查源头，逐渐揭开一段隐藏的过往。",
    ),
    (
        "formal",
        "formal-03",
        "冒险",
        "adventure-castle",
        "古堡里的一场冒险",
        "一道意外开启的暗门将主角引向地底，那里藏着古堡真正的历史。",
    ),
    (
        "practice",
        "practice-02",
        "相遇",
        "encounter-rain-cafe",
        "雨夜咖啡馆里的一次相遇",
        "共撑一把伞的陌生人留下一句话，让主角开始重新审视自己的选择。",
    ),
    (
        "formal",
        "formal-04",
        "相遇",
        "encounter-train",
        "火车上的一次相遇",
        "对座旅人的几句闲谈，让主角想起一件早已被自己刻意遗忘的往事。",
    ),
    (
        "formal",
        "formal-05",
        "相遇",
        "encounter-journey",
        "旅途中的一次相遇",
        "一个偶遇的同行者改变了原本的路线，也悄悄改变了主角看世界的方式。",
    ),
    (
        "formal",
        "formal-06",
        "相遇",
        "encounter-years-later",
        "多年以后的一次相遇",
        "久别重逢的两人在熟悉的地方相对，发现彼此都已不是当年的模样。",
    ),
    (
        "practice",
        "practice-03",
        "秘密",
        "secret-old-house",
        "老房子里的一个秘密",
        "整理旧物时翻出一个上锁的盒子，里面藏着家族从未提起过的故事。",
    ),
    (
        "formal",
        "formal-07",
        "秘密",
        "secret-friends",
        "朋友之间的一个秘密",
        "一句不经意的话让主角意识到，最亲近的人或许从未真正坦诚相对。",
    ),
    (
        "formal",
        "formal-08",
        "秘密",
        "secret-letter",
        "一封信里的一个秘密",
        "多年后才寄到的信揭开一段往事，让主角不得不重新理解某个人。",
    ),
    (
        "formal",
        "formal-09",
        "秘密",
        "secret-childhood",
        "童年时期的一个秘密",
        "回到故乡的主角想起一件被刻意遗忘的事，决定追问当年的真相。",
    ),
    (
        "practice",
        "practice-04",
        "比赛",
        "competition-campus",
        "校园里的一场比赛",
        "实力悬殊的对决中，主角逐渐发现胜负之外还有更重要的东西。",
    ),
    (
        "formal",
        "formal-10",
        "比赛",
        "competition-kitchen",
        "厨房里的一场比赛",
        "两代人各执一份食谱较劲，最终在味道里读出彼此未说出口的话。",
    ),
    (
        "formal",
        "formal-11",
        "比赛",
        "competition-street",
        "街头的一场比赛",
        "一场临时起意的较量将素不相识的人聚在一起，留下意想不到的余韵。",
    ),
    (
        "formal",
        "formal-12",
        "比赛",
        "competition-snow",
        "雪地里的一场比赛",
        "风雪中的角逐让主角面对极限，也让他看清自己真正想抵达的方向。",
    ),
    (
        "practice",
        "practice-05",
        "庆祝",
        "celebration-birthday",
        "生日的一次庆祝",
        "一份没有署名的礼物打乱了原本的节奏，引出一段被搁置已久的关系。",
    ),
    (
        "formal",
        "formal-13",
        "庆祝",
        "celebration-graduation",
        "毕业的一次庆祝",
        "合影定格的那一刻，几个朋友心照不宣地走向各自不同的远方。",
    ),
    (
        "formal",
        "formal-14",
        "庆祝",
        "celebration-victory",
        "胜利的一次庆祝",
        "欢呼散去后主角独自留在原地，开始思考这场胜利真正的代价。",
    ),
    (
        "formal",
        "formal-15",
        "庆祝",
        "celebration-festival",
        "节日的一次庆祝",
        "一家人围坐时一个空缺的位置勾起回忆，让团圆有了别样的分量。",
    ),
)


DEFAULT_MATERIAL_ROWS = tuple(
    {
        "phase": phase,
        "prompt_id": prompt_id,
        "theme": theme,
        "subpremise_id": subpremise_id,
        "premise_text": premise_text,
        "suggestion_text": suggestion_text,
        "suggestion_model": "built-in",
        "suggestion_generated_at": "2026-05-13",
        "generation_prompt_version": "builtin-v1",
        "difficulty": "",
        "condition_slot": f"theme{index // 4 + 1}-sub{index % 4 + 1}",
        "participant_slot": "",
        "notes": "",
    }
    for index, (phase, prompt_id, theme, subpremise_id, premise_text, suggestion_text) in enumerate(_STORIES)
)

DEFAULT_MATERIAL_PROMPT_IDS = tuple(row["prompt_id"] for row in DEFAULT_MATERIAL_ROWS)
